// Copyright 2025-2026 Benjamin Becker
// SPDX-License-Identifier: Apache-2.0

/**
 * Tests for SpecStory Parser and Transcript Infrastructure
 */

import { describe, it, expect } from 'vitest';
import {
  // Parser
  parseSpecStoryFile,
  parseSpecStorySlice,
  buildTranscriptMessages,
  filterNewMessages,
  extractSessionIdFromFilename,
  extractSessionUUID,
  SPECSTORY_ADAPTER_NAME,
  
  // Hash utilities
  computeContentHash,
  normalizeText,
  buildSourceKey,
  parseSourceKey,
  
  // Heuristics
  scoreMessage,
  speakerToMessageRole,
  stripInlineTags,
} from '../transcripts/index.js';

// =============================================================================
// Parser Tests
// =============================================================================

describe('SpecStory Parser', () => {
  const sampleMarkdown = `<!-- Generated by SpecStory -->

<!-- vscode Session 90dd218c-2287-496b-8ef4-880f78cec39d (2025-09-25 18:36Z) -->

# Project setup (2025-09-25 18:36Z)

_**User (2025-09-25 19:13Z)**_

Hello, please set up the project.

---

_**Assistant (copilot/gpt-4)**_

Sure! Here's the setup:

\`\`\`bash
npm init -y
\`\`\`

---

_**User (2025-09-25 19:25Z)**_

Thanks! Can you add TypeScript?

---
`;

  it('should extract session UUID from content', () => {
    const uuid = extractSessionUUID(sampleMarkdown);
    expect(uuid).toBe('90dd218c-2287-496b-8ef4-880f78cec39d');
  });

  it('should extract session ID from filename', () => {
    expect(extractSessionIdFromFilename('2025-09-25_18-36Z-project-setup.md'))
      .toBe('project-setup');
    
    expect(extractSessionIdFromFilename('random-file.md'))
      .toBe('random-file');
  });

  it('should parse messages from markdown', () => {
    const buffer = Buffer.from(sampleMarkdown, 'utf-8');
    const result = parseSpecStoryFile(buffer);
    
    expect(result.sessionId).toBe('90dd218c-2287-496b-8ef4-880f78cec39d');
    expect(result.rawMessages).toHaveLength(3);
    
    // First message - User
    expect(result.rawMessages[0].speaker).toBe('user');
    expect(result.rawMessages[0].ts).toBe('2025-09-25 19:13Z');
    expect(result.rawMessages[0].text).toContain('Hello');
    
    // Second message - Assistant
    expect(result.rawMessages[1].speaker).toBe('assistant');
    expect(result.rawMessages[1].model).toBe('copilot/gpt-4');
    expect(result.rawMessages[1].text).toContain('setup');
    
    // Third message - User
    expect(result.rawMessages[2].speaker).toBe('user');
    expect(result.rawMessages[2].text).toContain('TypeScript');
  });

  it('should track byte offsets correctly', () => {
    const buffer = Buffer.from(sampleMarkdown, 'utf-8');
    const result = parseSpecStoryFile(buffer);
    
    // Each message should have valid byte offsets
    for (const msg of result.rawMessages) {
      expect(msg.absHeaderOffset).toBeGreaterThanOrEqual(0);
      expect(msg.absContentEnd).toBeGreaterThan(msg.absHeaderOffset);
    }
    
    // Offsets should be monotonically increasing
    for (let i = 1; i < result.rawMessages.length; i++) {
      expect(result.rawMessages[i].absHeaderOffset)
        .toBeGreaterThan(result.rawMessages[i - 1].absHeaderOffset);
    }
  });

  it('should build transcript messages with seq numbers', () => {
    const buffer = Buffer.from(sampleMarkdown, 'utf-8');
    const result = parseSpecStoryFile(buffer);
    
    const messages = buildTranscriptMessages(
      result.rawMessages,
      result.sessionId,
      1,
      SPECSTORY_ADAPTER_NAME
    );
    
    expect(messages).toHaveLength(3);
    
    // Check sourceKey format
    expect(messages[0].sourceKey).toBe('specstory:90dd218c-2287-496b-8ef4-880f78cec39d:m:1');
    expect(messages[1].sourceKey).toBe('specstory:90dd218c-2287-496b-8ef4-880f78cec39d:m:2');
    expect(messages[2].sourceKey).toBe('specstory:90dd218c-2287-496b-8ef4-880f78cec39d:m:3');
    
    // Check id equals sourceKey
    expect(messages[0].id).toBe(messages[0].sourceKey);
    
    // Check seq numbers
    expect(messages[0].seq).toBe(1);
    expect(messages[1].seq).toBe(2);
    expect(messages[2].seq).toBe(3);
  });

  it('should filter messages by header offset', () => {
    const buffer = Buffer.from(sampleMarkdown, 'utf-8');
    const result = parseSpecStoryFile(buffer);
    
    // Filter to messages after the first one
    const threshold = result.rawMessages[0].absHeaderOffset;
    const newMessages = filterNewMessages(result.rawMessages, threshold);
    
    expect(newMessages).toHaveLength(2);
    expect(newMessages[0].speaker).toBe('assistant');
  });
});

// =============================================================================
// Hash Utility Tests
// =============================================================================

describe('Hash Utilities', () => {
  it('should compute consistent content hashes', () => {
    const hash1 = computeContentHash('Hello, world!');
    const hash2 = computeContentHash('Hello, world!');
    
    expect(hash1).toBe(hash2);
    expect(hash1).toHaveLength(64); // SHA256 hex
  });

  it('should normalize text for hashing', () => {
    // Whitespace normalization
    expect(normalizeText('  hello   world  ')).toBe('hello world');
    
    // Lowercase
    expect(normalizeText('Hello World')).toBe('hello world');
    
    // Multiple spaces
    expect(normalizeText('a    b\n\nc')).toBe('a b c');
  });

  it('should build valid source keys', () => {
    const key = buildSourceKey('specstory', 'session-123', 42);
    expect(key).toBe('specstory:session-123:m:42');
  });

  it('should parse source keys', () => {
    const parsed = parseSourceKey('specstory:session-123:m:42');
    
    expect(parsed).not.toBeNull();
    expect(parsed?.source).toBe('specstory');
    expect(parsed?.sessionId).toBe('session-123');
    expect(parsed?.seq).toBe(42);
  });

  it('should handle session IDs with colons', () => {
    const key = buildSourceKey('specstory', 'uuid:with:colons', 5);
    const parsed = parseSourceKey(key);
    
    expect(parsed?.sessionId).toBe('uuid:with:colons');
    expect(parsed?.seq).toBe(5);
  });

  it('should reject invalid source keys', () => {
    expect(parseSourceKey('invalid')).toBeNull();
    expect(parseSourceKey('a:b')).toBeNull();
    expect(parseSourceKey('a:b:m:notanumber')).toBeNull();
  });
});

// =============================================================================
// Heuristics Tests
// =============================================================================

describe('Heuristics', () => {
  it('should score user-like messages positively', () => {
    const result = scoreMessage('Can you help me fix this bug?');
    
    expect(result.score).toBeGreaterThan(0);
    expect(result.speaker).toBe('user');
    expect(result.signals).toContain('question');
  });

  it('should score assistant-like messages negatively', () => {
    const result = scoreMessage(`Here's the code you requested:

\`\`\`typescript
function hello() {
  console.log('Hello');
}
\`\`\`

This will print "Hello" to the console.`);
    
    expect(result.score).toBeLessThan(0);
    expect(result.speaker).toBe('assistant');
  });

  it('should detect imperatives as user messages', () => {
    const result = scoreMessage('Please create a new file called app.ts');
    
    expect(result.score).toBeGreaterThan(0);
    expect(result.signals).toContain('imperative');
  });

  it('should map speakers to message roles', () => {
    expect(speakerToMessageRole('user')).toBe('intent');
    expect(speakerToMessageRole('assistant')).toBe('implementation');
    expect(speakerToMessageRole('system')).toBe('meta');
    expect(speakerToMessageRole('tool')).toBe('runlog');
  });

  it('should strip inline role tags', () => {
    const text = '@iw role=spec This is a specification message';
    const stripped = stripInlineTags(text);
    
    expect(stripped).toBe('This is a specification message');
  });
});

// =============================================================================
// Incremental Parsing Tests
// =============================================================================

describe('Incremental Parsing', () => {
  it('should parse slice with correct offset tracking', () => {
    const fullContent = `<!-- vscode Session abc123 (2025-01-01 00:00Z) -->

_**User (2025-01-01 00:01Z)**_

First message

---

_**Assistant (gpt-4)**_

Second message

---

_**User (2025-01-01 00:02Z)**_

Third message
`;

    const fullBuffer = Buffer.from(fullContent, 'utf-8');
    
    // Parse full file first
    const fullResult = parseSpecStoryFile(fullBuffer);
    expect(fullResult.rawMessages).toHaveLength(3);
    
    // Now parse a slice starting from middle
    const sliceStart = fullResult.rawMessages[1].absHeaderOffset - 10;
    const sliceBuffer = fullBuffer.subarray(sliceStart);
    
    const sliceResult = parseSpecStorySlice(sliceBuffer, sliceStart, 'abc123');
    
    // Should find messages 2 and 3
    expect(sliceResult.rawMessages.length).toBeGreaterThanOrEqual(2);
    
    // Offsets should be absolute (not relative to slice)
    for (const msg of sliceResult.rawMessages) {
      expect(msg.absHeaderOffset).toBeGreaterThanOrEqual(sliceStart);
    }
  });
});
